version: '3.9'
services:

  server:
    build: 
      context: ./nginx
    container_name: server
    networks:
      - desafio_network
    tty: true
    ports:
      - 8080:80
 
  app:
    build:
      context: ./node
    container_name: app
    networks:
      - desafio_network
    tty: true
    entrypoint: node index.js
    volumes:
      - vol_app:/usr/src/app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafio
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio_network
  
networks:
  desafio_network:
    driver: bridge

volumes:
  vol_app: